# .github/workflows/sca-windows-owasp.yml
name: SCA - OWASP on Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  dependency-check:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Java (required for Dependency-Check)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Download OWASP Dependency-Check
      run: |
        Invoke-WebRequest -Uri https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip -OutFile dc.zip
        Expand-Archive -Path dc.zip -DestinationPath dc

    - name: Run Dependency-Check
      run: |
        .\dc\dependency-check\bin\dependency-check.bat --project "MyDotNetApp" --scan . --format HTML --out .
      
    - name: Upload SCA Report
      uses: actions/upload-artifact@v4
      with:
        name: DependencyCheck-Report
        path: dependency-check-report.html
